services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: climbed
      POSTGRES_PASSWORD: climbed
      POSTGRES_DB: climbed
    ports:
      - "5432:5432"
    volumes:
      - climbed_pg_data:/var/lib/postgresql/data

volumes:
  climbed_pg_data:
